source/accounts/urls.py
from django.urls import path

app_name = 'accounts'

urlpatterns = [

]

source/cpm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import ProjectListView, CreateProjectView, UpdateProjectView, ProjectDetailView, DeleteProjectView
from webapp.views import CreateLinkView, UpdateLinkView, DeleteLinkView

app_name = 'webapp'

urlpatterns = [
    path('', ProjectListView.as_view(), name='projects'),
    path('projects/create/', CreateProjectView.as_view(), name='create_project'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/update/', UpdateProjectView.as_view(), name='update_project'),
    path('projects/<int:pk>/delete/', DeleteProjectView.as_view(), name='delete_project'),
    path('projects/<int:pk>/links/create/', CreateLinkView.as_view(), name='create_link'),
    path('links/<int:pk>/update', UpdateLinkView.as_view(), name='update_link'),
    path('links/<int:pk>/delete/', DeleteLinkView.as_view(), name='delete_link')
]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', verbose_name="Аватар")

source/webapp/models/link.py
from django.db import models

types = [('Site', 'Сайт'), ('Discord', 'Дискорд'), ('Guild', 'Гильдия'), ('Guide', 'Гайд'), ('Other', 'Другое')]
SITE = types[0][0]


class Link(models.Model):
    type = models.CharField(max_length=100, choices=types, default=SITE, verbose_name='Тип')
    url = models.URLField(max_length=500, verbose_name='Адрес')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='links', verbose_name='Проект')

    def __str__(self):
        return f"{self.pk}. {self.type} - {self.project.name}"

    class Meta:
        db_table = "links"
        verbose_name = "Ссылка"
        verbose_name_plural = "Ссылки"

source/webapp/models/project.py
from django.db import models

statuses = [('Active', 'Активный'), ('Finished', 'Завершен'), ('Abandoned', 'Забросил')]
ACTIVE = statuses[0][0]
INACTIVE = statuses[0][0]
priorities = [('Tier 1', 'Тир 1'), ('Tier 2', 'Тир 2'), ('Tier 3', 'Тир 3'), ('Antifomo', 'Антифомо')]
TIER_1 = priorities[0][0]
TIER_2 = priorities[1][0]
TIER_3 = priorities[2][0]
ANTIFOMO = priorities[3][0]


class Project(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(null=True, blank=True, verbose_name='Описание')
    status = models.CharField(max_length=100, choices=statuses, default=ACTIVE, verbose_name='Статус')
    priority = models.CharField(max_length=100, choices=priorities, default=ANTIFOMO, verbose_name='Приоритет')
    info = models.TextField(null=True, blank=True, verbose_name='Инфа')
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f"{self.pk}. {self.name} - {self.status}"

    class Meta:
        db_table = "projects"
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"

source/webapp/forms/link.py
from django import forms

from webapp.models import Link


class LinkForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for v in self.visible_fields():
            v.field.widget.attrs["class"] = "form-control"
            v.field.widget.attrs["autocomplete"] = "off"

    class Meta:
        model = Link
        fields = ("type", "url")

source/webapp/forms/project.py
from django import forms

from webapp.models import Project


class ProjectForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for v in self.visible_fields():
            v.field.widget.attrs["class"] = "form-control"

    class Meta:
        model = Project
        fields = ("name", "description", "status", "priority", "info")

source/accounts/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/link.py
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView

from webapp.models import Link, Project
from webapp.forms import LinkForm


class CreateLinkView(CreateView):
    template_name = "link/create_link.html"
    form_class = LinkForm

    def dispatch(self, request, *args, **kwargs):
        self.project = get_object_or_404(Project, pk=self.kwargs.get('pk'))
        return super().dispatch(request, args, kwargs)

    def form_valid(self, form):
        link = form.save(commit=False)
        link.project = self.project
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.project.pk})


class UpdateLinkView(UpdateView):
    template_name = "link/update_link.html"
    form_class = LinkForm
    model = Link

    def get_success_url(self):
        return reverse('webapp:projects')


class DeleteLinkView(DeleteView):
    model = Link

    def get_success_url(self):
        return reverse('webapp:projects')

source/webapp/views/project.py
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView, TemplateView

from webapp.models import Project, priorities, TIER_1, TIER_2, TIER_3, ANTIFOMO, ACTIVE
from webapp.forms import ProjectForm



class ProjectListView(ListView):
    model = Project
    template_name = "project/projects_list.html"
    ordering = ['created_at']
    context_object_name = 'projects'

    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        tier_1_queryset = []
        tier_2_queryset = []
        tier_3_queryset = []
        antifomo_queryset = []

        non_active_projects = []

        for project in queryset:
            if project.status == ACTIVE:
                if project.priority == TIER_1:
                    tier_1_queryset.append(project)
                elif project.priority == TIER_2:
                    tier_2_queryset.append(project)
                elif project.priority == TIER_3:
                    tier_3_queryset.append(project)
                else:
                    antifomo_queryset.append(project)
            else:
                non_active_projects.append(project)

        sorted_queryset = [*tier_1_queryset, *tier_2_queryset, *tier_3_queryset, *antifomo_queryset, *non_active_projects]

        sort_order = self.request.GET.get('sort', 'desc')
        if sort_order == 'asc':
            queryset = sorted_queryset[::-1]
        else:
            queryset = sorted_queryset
        return queryset



class CreateProjectView(CreateView):
    template_name = "project/create_project.html"
    form_class = ProjectForm

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView):
    template_name = "project/project_detail.html"
    model = Project


class UpdateProjectView(UpdateView):
    template_name = "project/update_project.html"
    form_class = ProjectForm
    model = Project

    def get_success_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.object.pk})


class DeleteProjectView(DeleteView):
    model = Project

    def get_success_url(self):
        return reverse('webapp:projects')

source/webapp/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CPM</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
    <div class="container"><a class="navbar-brand" href="{% url 'webapp:projects' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'webapp:create_project' %}">Добавить
                        проект</a>
                </li>
            </ul>
        </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/link/create_link.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mb-3">Добавить ссылку</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

source/webapp/templates/link/delete_link.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

source/webapp/templates/link/update_link.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mb-3">Изменить ссылку</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Изменить' %}
    </form>
{% endblock %}

source/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}:</label></p>
    <p>{{ field }}</p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
{% endfor %}

<button type="submit" class="btn btn-primary" >{{ button_text }}</button>

source/webapp/templates/partial/pagination.html
<nav aria-label="..." class="d-flex mt-3">
     <ul class="pagination mx-auto">
         <li class="page-item">
             <a href="?{% if search %}{{ search }}&{% endif %}page=1" class="page-link">&laquo; В начало</a>
         </li>
         {% if page_obj.has_previous %}
             <li class="page-item">
                 <a href="?{% if search %}{{ search }}&{% endif %}page={{ page_obj.previous_page_number }}"
                    class="page-link">Назад</a>
             </li>
         {% else %}
             <li class="page-item disabled">
                 <span class="page-link">Назад</span>
             </li>
         {% endif %}
         <li class="page-item">
             <form class="form-control d-flex" method="get">
                 <input type="hidden" name="search" value="{{ search_value }}">
                 <label for="page">
                     Страница <input type="text" name="page" id="page" value="{{ page_obj.number }}" class="form-control">
                     из {{ page_obj.paginator.num_pages }}.
                 </label>
             </form>
         </li>
         {% if page_obj.has_next %}
             <li class="page-item">
                 <a href="?{% if search %}{{ search }}&{% endif %}page={{ page_obj.next_page_number }}"
                    class="page-link">Далее</a>
             </li>
         {% else %}
             <li class="page-item disabled">
                 <span class="page-link">Далее</span>
             </li>
         {% endif %}
         <li class="page-item">
             <a href="?{% if search %}{{ search }}&{% endif %}page={{ page_obj.paginator.num_pages }}" class="page-link">В
                 конец &raquo;</a>
         </li>
     </ul>
 </nav>

source/webapp/templates/project/create_project.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mb-3">Добавить проект</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Добавить' %}
    </form>
{% endblock %}

source/webapp/templates/project/delete_project_modal.html
<div class="modal fade" id="delete_modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #FA675F; color: white">
                <h5 class="modal-title" id="ModalLabel">Подтверждение удаления</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="fw-bold">Вы действительно хотите удалить этот проект?</p>
                <p>Это действие невозможно отменить, и вся связанная информация будет удалена.</p>
                <p>Пожалуйста, подтвердите, что вы хотите продолжить.</p>
            </div>
            <div class="modal-footer">
                <form method="post" action="" id="deleteForm">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </form>
            </div>
        </div>
    </div>
</div>

source/webapp/templates/project/project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h3 class="mb-3">Детали проекта {{ project.name }}</h3>

    <div class="info">
        <p>{{ project.description }}</p>
        <p>{{ project.status }}</p>
        <p>{{ project.priority }}</p>
        <p>{{ project.info }}</p>
    </div>

    <div class="links mb-2">
        <p>Ссылки:</p>

        <div>
            {% for link in project.links.all %}
                <p>{{ link.type }}: <a href="{{ link.url }}" target="_blank">{{ link.url }}</a></p>
            {% empty %}
                <p>Ссылок нет</p>
            {% endfor %}
        </div>

        <a href="{% url 'webapp:create_link' project.pk %}" class="btn btn-primary">Добавить ссылку</a>
    </div>

    <div class="actions">
        <a href="{% url 'webapp:update_project' project.pk %}" class="btn btn-success">Обновить проект</a>

        <button type="button" class="btn btn-danger" data-js="delete_btn"
                data-url="{% url 'webapp:delete_project' project.pk %}">
            Удалить проект
        </button>
    </div>

    {% include 'project/delete_project_modal.html' %}

    <script src="{% static 'js/delete_project.js' %}"></script>

{% endblock %}

source/webapp/templates/project/projects_list.html
{% extends 'base.html' %}
{% block content %}

<h3 class="mb-3">Ваши проекты</h3>

<div class="table-responsive">

    <div class="mb-2">
        <span>Сортировать:</span>
        <form method="get" class="d-inline">
            <select name="sort" class="form-select d-inline" onchange="this.form.submit()">
                <option value="desc" {% if request.GET.sort == 'desc' %}selected{% endif %}>От лучших к
                    худшим
                </option>
                <option value="asc" {% if request.GET.sort == 'asc' %}selected{% endif %}>От худших к
                    лучшим
                </option>
            </select>
        </form>
    </div>

    <table class="table table-bordered table-striped table-hover">
        <thead>
        <tr>
            <th scope="col">Название</th>
            <th scope="col">Статус</th>
            <th scope="col">Приоритет</th>

            <th scope="col">Ссылки</th>


            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for project in projects %}
        <tr>
            <td>{{ project.name }}</td>
            <td>{{ project.get_status_display }}</td>
            <td>{{ project.get_priority_display }}</td>

            <td>
                {% for link in project.links.all %}
                <p>{{ link.get_type_display }}: <a href="{{ link.url }}" target="_blank">{{ link.url }}</a></p>
                {% endfor %}
            </td>

            <td>
                <a href="{% url 'webapp:update_project' project.pk %}" class="btn btn-success">Изменить</a>
                <a href="{% url 'webapp:project_detail' project.pk %}" class="btn btn-primary">Детально</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
    {% include "partial/pagination.html" %}
{% endif %}
{% endblock %}

source/webapp/templates/project/update_project.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="mb-3">Изменить проект</h3>
    <form action="" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text='Изменить' %}
    </form>
{% endblock %}